services:
  web:
    image: ${IMAGE_NAME:-tocf-site}
    build:
      context: .
      target: runner
    working_dir: /app
    command: npm start
    ports:
      - "${PORT_WEB:-3000}:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - web_node_modules:/app/node_modules
      - web_cache:/app/.next
    container_name: ${COMPOSE_PROJECT_NAME:-site-club-tesla}-site

volumes:
  web_node_modules:
  web_cache: